// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmdMZPH9PDLXzMpEwtZh6dr9S2ieX2uLI',
    appId: '1:645904198760:web:aab10e762f2ea8d3c51fdd',
    messagingSenderId: '645904198760',
    projectId: 'tam-luy',
    authDomain: 'tam-luy.firebaseapp.com',
    storageBucket: 'tam-luy.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7m7bdbba9oOQCRs2ZTkr-vNEdKJNtTQc',
    appId: '1:645904198760:android:68ed9c551f2ceb43c51fdd',
    messagingSenderId: '645904198760',
    projectId: 'tam-luy',
    storageBucket: 'tam-luy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4rvcqd-_KIOPqOOdtdFcROcJFa5umxH4',
    appId: '1:645904198760:ios:05cb71978ef23185c51fdd',
    messagingSenderId: '645904198760',
    projectId: 'tam-luy',
    storageBucket: 'tam-luy.firebasestorage.app',
    iosBundleId: 'com.salait.tamluy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4rvcqd-_KIOPqOOdtdFcROcJFa5umxH4',
    appId: '1:645904198760:ios:7a64486db0dc522cc51fdd',
    messagingSenderId: '645904198760',
    projectId: 'tam-luy',
    storageBucket: 'tam-luy.firebasestorage.app',
    iosBundleId: 'com.example.tamLuy',
  );
}
